version: '3.3'

services: 
    wordpress:
        image: wordpress
        restart: always
        ports: 
            - 8080:80
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wpuser
            WORDPRESS_DB_PASSWORD: wppass
            WORDPRESS_DB_NAME: wpdb
            WORDPRESS_DEBUG: 1
        volumes: 
            - ./src/plugins:/var/www/html/wp-content/plugins
            - ./src/themes:/var/www/html/wp-content/themes
            - ./src/uploads:/var/www/html/wp-content/uploads

    db:
        image: mysql:5.7
        restart: always 
        environment: 
            MYSQL_DATABASE: wpdb
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: wppass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes: 
            - ./db:/var/lib/mysql

    adminer:
        depends_on: 
            - db
        image: adminer
        restart: always
        ports: 
            - 8889:8080

    

networks: 
    back:
        
volumes: 
    db:
